apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-k8s-ingress
  namespace: {{ default "spring-deploy" .Values.namespace }}
spec:
  rules:
  - http:
      paths:
      - path: /message
        pathType: Exact
        backend:
          service:
            name: springboot-k8s-svc
            port:
              number: 8080