apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: {{ .Values.service }}-service-database-persistent-volume-claim

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "300Mi" .Values.storage }}
