apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service }}-db-svc-auth
type: kubernetes.io/basic-auth
stringData:
  username: pguser
  password: pgpw
 
---
apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Values.service }}-service-postgres-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.service }}-service-postgres

  template:
    metadata:
      labels:
        component: {{ .Values.service }}-service-postgres
    spec:
      volumes:
        - name: {{ .Values.service }}-service-postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Values.service }}-service-database-persistent-volume-claim

      containers:
        - name: {{ .Values.service }}-service-postgres
          image: postgres:alpine
          ports:
            - containerPort: 5432

          volumeMounts:
            - name: {{ .Values.service }}-service-postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.service }}-db-svc-auth
                  key: username
            - name: POSTGRES_DB
              value: {{ .Values.service }}-svc-pgdb
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.service }}-db-svc-auth
                  key: password
