apiVersion: v1

kind: Service

metadata:
  name: {{ .Values.service }}-service-postgres-service

spec:
  selector:
    component: {{ .Values.service }}-service-postgres

  type: LoadBalancer

  ports:
    - port: 5432
      targetPort: 5432

