apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosip-{{ .Values.service }}
spec:
  selector:
    matchLabels:
      app: mosip-{{ .Values.service }}
  replicas: {{ default 1 .Values.replicas }}
  template:
    metadata:
      labels:
        app: mosip-{{ .Values.service }}
    spec:
      containers:
        - name: mosip-{{ .Values.service }}
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"mosip-auth-service-url": "http://20.84.34.69/authentication-service/upload", "mosip-registration-service-url": "http://20.84.34.69/registration-service", "spring": {"datasource": {"url": "jdbc:postgresql://{{ .Values.env.host }}:5432/{{ .Values.env.db }}", "username": "pguser", "password": "pgpw"}}, "server": {"servlet": {"context-path": "{{ .Values.env.baseurl }}"}}}'
