apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mosip-service-ingress
  namespace: mosip
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway


spec:
  rules:
  - http:
      paths:
      - path: /registration-service
        pathType: Prefix
        backend:
          service:
            name: mosip-registration-svc
            port:
              number: 8080
      - path: /frontend-service/booking
        pathType: Prefix
        backend:
          service:
            name: mosip-booking-frontend-svc
            port:
              number: 8080
      - path: /booking-service
        pathType: Prefix
        backend:
          service:
            name: mosip-booking-svc
            port:
              number: 8080
      - path: /attendance-service
        pathType: Prefix
        backend:
          service:
            name: mosip-attendance-svc
            port:
              number: 8080
      - path: /frontend-service/lec-attendance-ui
        pathType: Prefix
        backend:
          service:
            name: mosip-lec-attendance-frontend-svc
            port:
              number: 8080
      - path: /entry-service
        pathType: Prefix
        backend:
          service:
            name: mosip-entry-svc
            port:
              number: 8080
      - path: /authentication-service
        pathType: Prefix
        backend:
          service:
            name: mosip-authentication-svc
            port:
              number: 8080
      - path: /frontend-service/exam-attendance
        pathType: Prefix
        backend:
          service:
            name: mosip-exam-attendance-frontend-svc
            port:
              number: 8080
