apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mosip-{{ .Values.service }}
spec:
  selector:
    matchLabels:
      app: mosip-{{ .Values.service }}
  replicas: {{ default 1 .Values.replicas }}
  template:
    metadata:
      labels:
        app: mosip-{{ .Values.service }}
    spec:
      containers:
        - name: mosip-{{ .Values.service }}
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080 
          env:
          - name: DB_HOST
            value: '{{ .Values.env.host }}'
          - name: DB_USER
            value: 'pguser'
          - name: DB_NAME
            value: '{{ .Values.env.db }}'
          - name: DB_PW
            value: pgpw
          - name: BASE_URL
            value: '{{ .Values.env.baseurl }}'
          - name: DB_DIALECT
            value: 'postgres'