trigger:
  branches:
    include:
      - main  # Change this to match your branch name

pool:
  vmImage: 'ubuntu-latest'
variables:
  ImageName: 'mosip/sample-service:$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build and push Docker image
        steps:
          - task: Docker@1
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'Docker Hub'
              command: 'Build an image'
              dockerFile: './src/sampleDockerfile'
              imageName: '$(ImageName)'
              useDefaultContext: false
              buildContext: './src'
            displayName: 'Build the Docker image'

          - task: Docker@1
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'Docker Hub'
              command: 'Push an image'
              imageName: '$(ImageName)'
            condition: succeeded()
            displayName: 'Push the Docker image to Dockerhub'

