trigger:
  branches:
    include:
      - main  # Change this to match your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
          echo "Hello World"