trigger:
  branches:
    include:
      - main  # Change this to match your branch name

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: TestJob
    displayName: 'Run Tests'
    steps:
      - script: echo Running tests...
        displayName: 'Run Test Script'