name: assets-upload CI/CD

on:
  push:
    branches: [ "main" ,"krishan-CI/CD"]
  workflow_dispatch:
env:
      AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=myresourcegroupb3fd;AccountKey=Zn4KkaZ1y7xzBQZjpuT/BPSwqiS/HodULtnZDT2hvGnG3TpNEZeqy/WcwtvQ0podBPGF2oNAHBN++AStkUu+5w==;EndpointSuffix=core.windows.net"
      #${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      BLOB_STORAGE_CONTAINER_NAME: "demo-public"
      #${{ secrets.BLOB_STORAGE_CONTAINER_NAME }}  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      
      #To install required dependencies
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
        with:
         python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f .github/workflows/requirements.txt ]; then pip install -r .github/workflows/requirements.txt; fi
      - name: Set environment variables
        run: |
          echo  ${{env.AZURE_STORAGE_CONNECTION_STRING}}
          echo  ${{env.BLOB_STORAGE_CONTAINER_NAME}}
      #environment variables successfully assigned    
      - name: Get changed & added assets
        id: changed-files-specific
        uses: tj-actions/changed-files@v37
        with:
          files: "**/assets/**"
      - name: Run step if any assest(s) in the assets folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
            echo  ${{env.AZURE_STORAGE_CONNECTION_STRING}}
            echo  ${{env.BLOB_STORAGE_CONTAINER_NAME}}
            for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}
            do
             python .github/workflows/assets-upload-script.py $file
            done


